server:
  port: 8098

spring:
    mvc:
        view:
            prefix: /WEB-INF/
            suffix: .jsp
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/mybatisprac
        username: root
        password: root

mybatis:
  type-aliases-package: com.example.mybatiscrudprac.domain
# mybatis:
#   mapper-locations: classpath:/mapper/**/*.xml
#   type-aliases-package: com.example.mybatiscurdprac.domain
#   configuration:
#     map-underscore-to-camel-case: true

# logging:
#   level:
#     com.example.mybatiscurdprac: debug
#     org.mybatis: debug
#     java.sql: debug
